// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetBootstrap() {
  return window['go']['main']['FrontendBridge']['GetBootstrap']();
}

export function UpdateChannel(arg1) {
  return window['go']['main']['FrontendBridge']['UpdateChannel'](arg1);
}
