// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {frontendbridge} from '../models';

export function AddChannel(arg1:frontendbridge.ChannelAddInput):Promise<frontendbridge.Channel>;

export function GetBootstrap():Promise<frontendbridge.BootstrapPayload>;

export function RemoveChannel(arg1:string):Promise<void>;

export function UpdateChannel(arg1:frontendbridge.ChannelUpdateInput):Promise<frontendbridge.Channel>;

export function UpdateKeywords(arg1:Array<frontendbridge.KeywordRuleInput>):Promise<void>;

export function UpdateOSC(arg1:frontendbridge.OSCSettingsInput):Promise<void>;
