// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {frontendbridge} from '../models';

export function GetBootstrap():Promise<frontendbridge.BootstrapPayload>;

export function UpdateChannel(arg1:frontendbridge.ChannelUpdateInput):Promise<frontendbridge.Channel>;
