// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddChannel(arg1) {
  return window['go']['main']['FrontendBridge']['AddChannel'](arg1);
}

export function GetBootstrap() {
  return window['go']['main']['FrontendBridge']['GetBootstrap']();
}

export function RemoveChannel(arg1) {
  return window['go']['main']['FrontendBridge']['RemoveChannel'](arg1);
}

export function UpdateChannel(arg1) {
  return window['go']['main']['FrontendBridge']['UpdateChannel'](arg1);
}

export function UpdateKeywords(arg1) {
  return window['go']['main']['FrontendBridge']['UpdateKeywords'](arg1);
}

export function UpdateOSC(arg1) {
  return window['go']['main']['FrontendBridge']['UpdateOSC'](arg1);
}
